// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.22.2
// source: tcp_message.proto

package tcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TcpMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code          int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpMessage) Reset() {
	*x = TcpMessage{}
	mi := &file_tcp_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpMessage) ProtoMessage() {}

func (x *TcpMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tcp_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpMessage.ProtoReflect.Descriptor instead.
func (*TcpMessage) Descriptor() ([]byte, []int) {
	return file_tcp_message_proto_rawDescGZIP(), []int{0}
}

func (x *TcpMessage) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *TcpMessage) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TcpMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *TcpMessage) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TcpMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TcpMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TcpMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_tcp_message_proto protoreflect.FileDescriptor

const file_tcp_message_proto_rawDesc = "" +
	"\n" +
	"\x11tcp_message.proto\x12\x03tcp\"\x9f\x01\n" +
	"\n" +
	"TcpMessage\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x06 \x01(\tR\x03msg\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04dataB%Z#github.com/aluka-7/game-gateway/tcpb\x06proto3"

var (
	file_tcp_message_proto_rawDescOnce sync.Once
	file_tcp_message_proto_rawDescData []byte
)

func file_tcp_message_proto_rawDescGZIP() []byte {
	file_tcp_message_proto_rawDescOnce.Do(func() {
		file_tcp_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tcp_message_proto_rawDesc), len(file_tcp_message_proto_rawDesc)))
	})
	return file_tcp_message_proto_rawDescData
}

var file_tcp_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tcp_message_proto_goTypes = []any{
	(*TcpMessage)(nil), // 0: tcp.TcpMessage
}
var file_tcp_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tcp_message_proto_init() }
func file_tcp_message_proto_init() {
	if File_tcp_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tcp_message_proto_rawDesc), len(file_tcp_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tcp_message_proto_goTypes,
		DependencyIndexes: file_tcp_message_proto_depIdxs,
		MessageInfos:      file_tcp_message_proto_msgTypes,
	}.Build()
	File_tcp_message_proto = out.File
	file_tcp_message_proto_goTypes = nil
	file_tcp_message_proto_depIdxs = nil
}
