// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/aluka-7/cache"
	"github.com/aluka-7/game-gateway/dto"
	"github.com/aluka-7/game-gateway/server"
	"github.com/panjf2000/gnet/v2"
)

// Injectors from wire.go:

func InitializeWsServer(gatewayConfig *dto.GatewayConfig, provider cache.Provider, string2 string) gnet.EventHandler {
	eventHandler := server.NewWsServer(gatewayConfig, provider, string2)
	return eventHandler
}

// wire.go:

const (
	SystemId = "10000"
)
